version: "3"
services:

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - backend
    depends_on:
      - micrometer
      - alertmanager
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  micrometer:
    image: micrometer-demo
    ports:
      - "8080:8080"
    networks:
      - backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  backend: